// Code generated by protoc-gen-coredge-sdk. DO NOT EDIT.
// source: template.proto

/*
Package workflow is auto generated SDK module

It provides auto generated functions to perform operations
using APIs defined as part of protobuf
*/
package workflow

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/coredgeio/gosdkclient"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
)

type WorkflowTemplateApiSdkClient interface {
	ListTemplates(req *TemplateListReq) (*TemplateListResp, error)
	CreateTemplate(req *TemplateCreateReq) (*TemplateCreateResp, error)
	GetTemplate(req *TemplateGetReq) (*TemplateGetResp, error)
	UpdateTemplate(req *TemplateUpdateReq) (*TemplateUpdateResp, error)
	DeleteTemplate(req *TemplateDeleteReq) (*TemplateDeleteResp, error)
	ExecuteTemplate(req *TemplateExecuteReq) (*TemplateExecuteResp, error)
}

type implWorkflowTemplateApiClient struct {
	client     gosdkclient.SdkClient
	pathPrefix string
}

func NewWorkflowTemplateApiSdkClient(client gosdkclient.SdkClient) WorkflowTemplateApiSdkClient {
	return &implWorkflowTemplateApiClient{
		client: client,
	}
}

func (c *implWorkflowTemplateApiClient) ListTemplates(req *TemplateListReq) (*TemplateListResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/templates"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	marshaller := &runtime.JSONPb{}
	r, _ := http.NewRequest("GET", subUrl, nil)
	q := url.Values{}
	q.Add("offset", fmt.Sprintf("%v", req.Offset))
	q.Add("limit", fmt.Sprintf("%v", req.Limit))
	q.Add("search", fmt.Sprintf("%v", req.Search))
	r.URL.RawQuery = q.Encode()
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateListResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}

func (c *implWorkflowTemplateApiClient) CreateTemplate(req *TemplateCreateReq) (*TemplateCreateResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/template"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	marshaller := &runtime.JSONPb{}
	jsonData, _ := marshaller.Marshal(req)
	r, _ := http.NewRequest("POST", subUrl, bytes.NewBuffer(jsonData))
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateCreateResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}

func (c *implWorkflowTemplateApiClient) GetTemplate(req *TemplateGetReq) (*TemplateGetResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/template/{name}"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	subUrl = strings.Replace(subUrl, "{"+"name"+"}", fmt.Sprintf("%v", req.Name), -1)
	marshaller := &runtime.JSONPb{}
	r, _ := http.NewRequest("GET", subUrl, nil)
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateGetResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}

func (c *implWorkflowTemplateApiClient) UpdateTemplate(req *TemplateUpdateReq) (*TemplateUpdateResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/template/{name}"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	subUrl = strings.Replace(subUrl, "{"+"name"+"}", fmt.Sprintf("%v", req.Name), -1)
	marshaller := &runtime.JSONPb{}
	jsonData, _ := marshaller.Marshal(req)
	r, _ := http.NewRequest("PUT", subUrl, bytes.NewBuffer(jsonData))
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateUpdateResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}

func (c *implWorkflowTemplateApiClient) DeleteTemplate(req *TemplateDeleteReq) (*TemplateDeleteResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/template/{name}"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	subUrl = strings.Replace(subUrl, "{"+"name"+"}", fmt.Sprintf("%v", req.Name), -1)
	marshaller := &runtime.JSONPb{}
	r, _ := http.NewRequest("DELETE", subUrl, nil)
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateDeleteResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}

func (c *implWorkflowTemplateApiClient) ExecuteTemplate(req *TemplateExecuteReq) (*TemplateExecuteResp, error) {
	// TODO(prabhjot) we are ignoring the error here for the time being
	subUrl := "/api/workflow/v1/domain/{domain}/project/{project}/template/{name}/execute"
	subUrl = strings.Replace(subUrl, "{"+"domain"+"}", fmt.Sprintf("%v", req.Domain), -1)
	subUrl = strings.Replace(subUrl, "{"+"project"+"}", fmt.Sprintf("%v", req.Project), -1)
	subUrl = strings.Replace(subUrl, "{"+"name"+"}", fmt.Sprintf("%v", req.Name), -1)
	marshaller := &runtime.JSONPb{}
	jsonData, _ := marshaller.Marshal(req)
	r, _ := http.NewRequest("POST", subUrl, bytes.NewBuffer(jsonData))
	r.Header.Set("Content-Type", "application/json")
	resp, err := c.client.PerformReq(r)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	obj := &TemplateExecuteResp{}
	err = marshaller.Unmarshal(bodyBytes, obj)
	if err != nil {
		return nil, err
	}

	return obj, nil
}
