apiVersion: v1
kind: Secret
metadata:
  name: configdb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: c2lnbWE= # sigma
  password: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  name: config-replica-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ (.Files.Glob "files/auth").AsSecrets | indent 2 }}
---
{{- if and (not .Values.global.keycloak.internal) ( .Values.global.keycloak.override.creds) }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-override-creds
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.global.keycloak.override.creds.pass }}
  username: {{ .Values.global.keycloak.override.creds.user }}
type: Opaque
{{- end }}
