apiVersion: v1
kind: Service
metadata:
  name: workflow-configdb
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.configDB.metrics.enabled }}
    prometheus.io/path: /metrics
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
  {{- end }}
spec:
  type: {{ .Values.configDB.service.type }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
    {{- if .Values.configDB.metrics.enabled }}
    - name: metrics
      port: 9216
      protocol: TCP
      targetPort: 9216
    {{- end }}
  selector:
      app: configdb
---
apiVersion: v1
kind: Service
metadata:
  name: configdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: configdb
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-metricsdb
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.configDB.metrics.enabled }}
    prometheus.io/path: /metrics
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
  {{- end }}
spec:
  type: {{ .Values.metricsDB.service.type }}
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
    {{- if .Values.metricsDB.metrics.enabled }}
    - name: metrics
      port: 9216
      protocol: TCP
      targetPort: 9216
    {{- end }}
  selector:
      app: metricsdb
---
apiVersion: v1
kind: Service
metadata:
  name: metricsdb
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
      app: metricsdb
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: workflow-manager
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: websocket
      port: 9080
      targetPort: 9080
  selector:
    app: workflow-manager
