apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: vm-console
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vm-console
  template:
    metadata:
      labels:
        app: vm-console
    spec:
      dnsPolicy: ClusterFirst 
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: vm-console
        image: {{ .Values.global.repository }}/{{ .Values.image }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }} 
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: conf
          readOnly: true
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        {{- if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "loadbalancer") }}
        {{- if .Values.global.frontend.vmconsole.tlsSecret }}
        - name: vmconsole-certs-vol
          readOnly: true
          mountPath: /etc/nginx/certs/ingress
        {{- end }}
        {{- end }}
      volumes:
      - name: conf
        configMap:
          name: vm-console-conf
      {{- if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "loadbalancer") }}
      {{- if .Values.global.frontend.vmconsole.tlsSecret }}
      - name: vmconsole-certs-vol
        secret:
          secretName: {{ .Values.global.frontend.vmconsole.tlsSecret }}
      {{- end }}
      {{- end }}