apiVersion: v1
kind: Service
metadata:
  name: vm-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: vm-console
spec:
  {{- if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "ingress") }}
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  {{- else if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "loadbalancer") }}
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: {{ .Values.global.frontend.vmconsole.nodePort }}
  {{- else }}
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: {{ .Values.global.frontend.vmconsole.nodePort }}
  {{- end }}
  selector:
    app: vm-console