apiVersion: v1
kind: Service
metadata:
  name: vm-console
  namespace: {{ .Release.Namespace }}
  labels:
    app: vm-console
spec:
  {{- if .Values.global.dnsEnabled }}
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  {{- else }}
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: {{ .Values.global.frontend.vmconsole.nodePort }}
  {{- end }}
  selector:
    app: vm-console