## Necessary rbac required to manage checks for ccp postgresql HA custom resource
---
{{- if not .Values.global.postgresql.external.host }}
{{- if and (.Capabilities.APIVersions.Has "acid.zalan.do/v1") (not .Values.global.postgresql.architecture.standalone) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccs-postgresql-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ccs-postgresql-operator
  namespace: {{ .Release.Namespace }}
rules:
# all verbs allowed for custom operator resources
- apiGroups:
  - acid.zalan.do
  resources:
  - postgresqls
  - postgresqls/status
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
# to CRUD services to point to Postgres cluster instances
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - delete
  - get
  - patch
  - update
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ccs-postgresql-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ccs-postgresql-operator
subjects:
- kind: ServiceAccount
  name: ccs-postgresql-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}