{{- if not .Values.global.postgresql.external.host }}
{{- if not .Values.global.postgresql.architecture.standalone }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlHA.creds.user }}.ccs-postgresql-cluster.credentials.postgresql.acid.zalan.do
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.postgresqlHA.creds.pass | b64enc | quote }}
  username: {{ .Values.postgresqlHA.creds.user | b64enc | quote }}
{{- end }}
{{- end }}