apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-registry-key
  namespace: {{ .Release.Namespace }}
data:
  .dockercfg: {{ include "repoRegistryKey.secret" . }}
type: kubernetes.io/dockercfg
