apiVersion: v1
kind: Service
metadata:
  name: orbiter-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    orbiter.coredge.io: auth
  ports:
  - protocol: TCP
    port: 8060
    targetPort: 8060
    name: auth
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: api
{{- if .Values.global.tenantManagement.register.enabled }}
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: public-api
{{- end }}
