apiVersion: v1
kind: ServiceAccount
metadata:
  name: compass-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-compass-controller
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-compass-controller
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: compass-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-compass-controller
  apiGroup: rbac.authorization.k8s.io
