apiVersion: v1
kind: Service
metadata:
  name: tenant-management-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: tenant-management-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tenant-management-service
