apiVersion: v1
kind: ConfigMap
metadata:
  name: baremetal-manager-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    mongodb:
      host: compass-configdb
      port: 27017
    metricsdb:
      host: compass-metricsdb
      port: 27017
    maas:
      url: {{ .Values.maas.url }}
      apikey: {{ .Values.maas.apikey }}
{{- if .Values.fabric.enabled }}
    fabric:
      virtualIPs:
        first: {{ .Values.fabric.virtualIPs.first }}
        last: {{ .Values.fabric.virtualIPs.last }}
{{- end }}
    events:
      limits:
        maxSize: 1000000 # max memory allowed to be used in bytes for events per domain
        maxEntries: 5000 # max number of entries allowed to be used for events per domain
