apiVersion: v1
kind: Service
metadata:
  name: baremetal-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: baremetal-manager
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: websocket
    port: 9080
    targetPort: 9080
    protocol: TCP
  selector:
    app: baremetal-manager
