apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgadmin
spec:
  {{- if (eq .Values.service.type "NodePort") }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
      app: pgadmin