apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |-
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    server {
        {{- if not .Values.global.domain  }}
        listen       8080{{- if .Values.global.proxyProtocol.enabled }} proxy_protocol{{- end }};
        listen       [::]:8080{{- if .Values.global.proxyProtocol.enabled }} proxy_protocol{{- end }};
        {{- else }}
        listen       8443 ssl{{- if .Values.global.proxyProtocol.enabled }} proxy_protocol{{- end }};
        listen       [::]:8443 ssl{{- if .Values.global.proxyProtocol.enabled }} proxy_protocol{{- end }};
        {{- end }}
        server_name  _;
        client_max_body_size 2M;
        proxy_busy_buffers_size   128k;
        proxy_buffers   64 64k;
        proxy_buffer_size   128k;
        {{- if .Values.global.domain  }}
        ssl_certificate /etc/nginx/certs/ingress/tls.crt;
        ssl_certificate_key /etc/nginx/certs/ingress/tls.key;
        {{- end }}

        proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address
        proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
        proxy_set_header Host $http_host;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /index.html;
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
        }

        location /api {
            proxy_pass http://orbiter-auth:8060;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
        }

        location /ws {
            proxy_pass http://orbiter-auth:8060;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /auth/resources {
            proxy_pass {{ include "helper.keycloakHttpEndpoint" . }};
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
        }

        location /auth/realms/master {
            deny all;
        }

        location /auth/realms {
            proxy_pass {{ include "helper.keycloakHttpEndpoint" . }};
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
        }

        {{- if .Values.global.containerRegistry.enabled }}
        location /v2/ {
            proxy_pass  http://container-registry:8020;
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
            
            # Setting client_max_body_size to a high value (10G) 
            # to accommodate large uploads for the container registry.
            client_max_body_size 10G;
        }

        location /api/registry/auth {
            proxy_pass  http://container-registry:8070;
            add_header 'Cache-Control' 'no-store, no-cache, max-age=10';
        }
        {{- end }}

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
