apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: {{ .Release.Namespace }}
  labels:
    app: admin-portal
spec:
  {{- if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "ingress") }}
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  {{- else if and ( .Values.global.dnsEnabled) (eq .Values.global.serviceExposure.type "loadbalancer") }}
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    nodePort: {{ .Values.adminportal.service.nodePort }}
  {{- else }}
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: {{ .Values.adminportal.service.nodePort }}
  {{- end }}
  selector:
    app: admin-portal
---
apiVersion: v1
kind: Service
metadata:
  name: admin-platform
  namespace: {{ .Release.Namespace }}
  labels:
    app: admin-platform
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: admin-platform
---
apiVersion: v1
kind: Service
metadata:
  name: admin-platform-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: admin-platform-celery
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: admin-platform-celery