apiVersion: v1
kind: Service
metadata:
  name: user-portal
  namespace: {{ .Release.Namespace }}
{{- if eq "AWS" .Values.global.environment }}
{{- if .Values.global.proxyProtocol.enabled  }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
{{- end }}
{{- end }}
spec:
  ports:
{{- if .Values.global.dnsEnabled }}
  - name: bootstrap
    port: 8030
    targetPort: 8030
    nodePort: 30230
  - name: controller
    port: 8040
    targetPort: 8040
    nodePort: 30240
{{- end }}
{{- if not .Values.global.kubectl.tokenAccess.enabled  }}
  - name: kubectl
    port: 6443
    targetPort: 6443
{{- end }}
  - name: http
{{- if not .Values.global.dnsEnabled }}
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  type: NodePort
{{ else }}
    port: 443
    targetPort: 443
    nodePort: {{ .Values.service.nodePort }}
  type: LoadBalancer
{{ end }}
  selector:
    app: user-portal