apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutron-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: neutron-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: neutron-service
  template:
    metadata: 
      labels:
        app: neutron-service
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      initContainers:
      {{ include "helper.postgresql.pgready" . }}
      containers:
      - name: network
        image: {{ .Values.global.repository }}/{{ .Values.image }}:{{ .Values.global.releaseTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: platform-api-config   
        - configMapRef:
            name: redis-config
        {{- if .Values.global.events.enabled }}
        - configMapRef:
            name: ccp-events-config
        {{- end }}
        {{- if .Values.certificates.enabled }}
        - configMapRef:
            name: certificates-manager-config
        {{- end }}
        - secretRef:
            name: ccs-postgres-config
        - secretRef:
            name: ccs-auditdb-config
        env:
          - name: ENABLED_MODULES
            value: {{ .Values.enabledServices | quote }}     
          - name: POSTGRES_DB
            value: "cloud"
          - name: FLASK_CONFIG
            value: {{ .Values.global.flaskConfig }}
          - name: CACHING_ENABLED
            value: "false"
        volumeMounts:
          - name: provider-vol
            readOnly: true
            mountPath: /etc/yntraa/
          - name: api-conf-vol
            mountPath: /etc/api/
          - name: openstack-templates-vol
            mountPath: /etc/yntraa/app/extensions/providers/templates/openstack/
          - name: openstack-templates-lib-vol
            mountPath: /etc/yntraa/app/extensions/providers/templates/openstack/lib/
      volumeMounts:
          - name: platform-config
            readOnly: true
            mountPath: /etc/yntraa/
      volumes:
        - name: platform-config
          projected:
            sources:
            - secret:
                name: ccs-super-admin-config
---
{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutron-service-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: neutron-service-celery
spec:
  replicas: {{ .Values.celery.replicaCount }}
  selector:
    matchLabels:
      app: neutron-service-celery
  template:
    metadata: 
      labels:
        app: neutron-service-celery
    spec:
      dnsPolicy: ClusterFirst
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      initContainers:
      {{ include "helper.postgresql.pgready" . }}
      containers:
      - name: network-celery
        image: {{ .Values.global.repository }}/{{ .Values.image }}:{{ .Values.global.releaseTag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        {{- if .Values.celery.command }}              
        command:
          - "/bin/sh"
          - "-c"
          - "{{ .Values.celery.command }}"
        {{- end }}
        resources: 
          {{- toYaml .Values.celery.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: platform-api-config  
        - configMapRef:
            name: redis-config 
        {{- if .Values.certificates.enabled }}
        - configMapRef:
            name: certificates-manager-config
        {{- end }}
        {{- if .Values.global.events.enabled }}
        - configMapRef:
            name: ccp-events-config
        {{- end }}
        - secretRef:
            name: ccs-postgres-config
        - secretRef:
            name: ccs-auditdb-config
        env:
          - name: ENABLED_MODULES
            value: {{ .Values.enabledServices | quote }}     
          - name: POSTGRES_DB
            value: "cloud"
          - name: FLASK_CONFIG
            value: {{ .Values.global.flaskConfig }}
          - name: CACHING_ENABLED
            value: "false"
{{- end }}