apiVersion: v1
kind: Service
metadata:
  name: orbiter-metering
  namespace: {{ .Release.Namespace }}
  labels:
    app: orbiter-metering
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: websocket
    port: 9080
    targetPort: 9080
    protocol: TCP
  - name: ccp
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: orbiter-metering
