apiVersion: v1
kind: ConfigMap
metadata:
  name: certificates-manager-config
  namespace: {{ .Release.Namespace }}
data:
  VAULT_ENABLED: "true"
  VAULT_ADDR: {{ .Values.vault.url | quote }}
  VAULT_TOKEN: {{ .Values.vault.token | quote }}
  VAULT_KV_PATH: {{ .Values.vault.kvPath | quote }}
  VERIFY_VAULT_SSL: {{ .Values.vault.ssl | quote }}