apiVersion: v1
kind: Service
metadata:
  name: certificates-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: certificates-manager
spec:
  type: ClusterIP
  ports:
  - port: 7140
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: certificates-manager