apiVersion: v1
kind: Service
metadata:
  name: compute-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: compute-service
spec:
  type: ClusterIP
  ports:
  - port: 7110
    targetPort: 5000
    protocol: TCP
  selector:
      app: compute-service
---
apiVersion: v1
kind: Service
metadata:
  name: compute-service-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: compute-service-celery
spec:
  type: ClusterIP
  ports:
  - port: 7110
    targetPort: 5000
    protocol: TCP
  selector:
      app: compute-service-celery