{{- if and ( .Values.smtp.username) ( .Values.smtp.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: notiication-smtp-creds
type: Opaque
data:
  smtp-username: {{ .Values.smtp.username | b64enc }}
  smtp-password: {{ .Values.smtp.password | b64enc }}
{{- end }}