apiVersion: v1
kind: Service
metadata:
  name: notiication-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: notiication-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: notiication-service