apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-manager-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    mongodb:
      host: compass-configdb
      port: 27017
    metricsdb:
      host: compass-metricsdb
      port: 27017
    events:
      limits:
        maxSize: 1000000 # max memory allowed to be used in bytes for events per domain
        maxEntries: 5000 # max number of entries allowed to be used for events per domain
    cloudAccount:
      healthcheckInterval: 300 # value for health check interval (in seconds)
    s3Endpoint:
      healthCheckInterval: 300
