apiVersion: v1
kind: Service
metadata:
  name: cloud-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloud-manager
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cloud-manager
