apiVersion: v1
kind: Service
metadata:
  name: storage-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app: storage-plugin
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: storage-plugin
