apiVersion: v1
kind: Service
metadata:
  name: archival-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app: archival-storage
spec:
  type: ClusterIP
  ports:
  - port: 7170
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: archival-storage