apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    mongodb:
      host: workflow-configdb
      port: 27017
    metricsdb:
      host: workflow-metricsdb
      port: 27017
    events:
      limits:
        maxSize: 1000000 # max memory allowed to be used in bytes for events per domain
        maxEntries: 5000 # max number of entries allowed to be used for events per domain
    storage:
      bucketPrefix: {{ .Values.storage.bucketPrefix }}
{{- if .Values.storage.cephS3 }}
      cephS3:
        userId: {{ .Values.storage.cephS3.userId }}
        endpoint: {{ .Values.storage.cephS3.endpoint }}
        accessKey: {{ .Values.storage.cephS3.accessKey }}
        secretKey: {{ .Values.storage.cephS3.secretKey }}
{{- end }}
{{- if .Values.storage.s3 }}
      s3:
        endpoint: {{ .Values.storage.s3.endpoint }}
        accessKey: {{ .Values.storage.s3.accessKey }}
        secretKey: {{ .Values.storage.s3.secretKey }}
{{- end }}
{{- if .Values.storage.ecs }}
      ecs:
        endpoint: {{ .Values.storage.ecs.endpoint }}
        s3Endpoint: {{ .Values.storage.ecs.s3Endpoint }}
        username: {{ .Values.storage.ecs.username }}
        password: {{ .Values.storage.ecs.password }}
        accessKey: {{ .Values.storage.ecs.accessKey }}
        secretKey: {{ .Values.storage.ecs.secretKey }}
        namespace: {{ .Values.storage.ecs.namespace }}
{{- end }}
