apiVersion: v1
kind: ConfigMap
metadata:
  name: network-manager-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    mongodb:
      host: compass-configdb
      port: 27017
    metricsdb:
      host: compass-metricsdb
      port: 27017
    providerinfo:
      servicetoken: {{ .Values.providerinfo.servicetoken }}
      providername: {{ .Values.providerinfo.providername }}
      vnistart: {{ .Values.providerinfo.vnistart }}
      vniend: {{ .Values.providerinfo.vniend }}
      vlanstart: {{ .Values.providerinfo.vlanstart }}
      vlanend: {{ .Values.providerinfo.vlanend }}

