apiVersion: v1
kind: Service
metadata:
  name: volume-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: volume-service
spec:
  type: ClusterIP
  ports:
  - port: 7120
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: volume-service
---
apiVersion: v1
kind: Service
metadata:
  name: volume-service-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: volume-service-celery
spec:
  type: ClusterIP
  ports:
  - port: 7120
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: volume-service-celery