apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ .Values.adminCredentials.password }}
  username: {{ .Values.adminCredentials.username }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-pg
  namespace: {{ .Release.Namespace }}
stringData:
  password: qdYfHbqUPmwtE9dB
  username: root
type: Opaque
