global:
  # indicates usage of external ingress, currently also acts as a
  # switch to indicate use of domain configuration
  dnsEnabled: &dnsEnabled false

  # Ingress claas to be defined to Ingress configuration 
  ingressClass: &ingressClass ""

  # repository from where the controller images are pulled for
  # controller
  repository: &repository coredgeio

  # this field is considered only when UseDailyBuilds is set to be false
  # provides configuration of build tag to be used for container images
  releaseTag: &releaseTag latest

  # image pull policy to be used
  imagePullPolicy: &imagePolicy Always

  # external IP for controller, relevant, when domain is not
  # configured to allow generation of server certificate validity using
  # this IP address
  externalIP: &controllerIP 127.0.0.1

  # Flask Config (Development OR Production)
  # TEMPORARY
  flaskConfig: "production"

  # keycloak realm to be used as the root
  rootRealm: &rootRealm "cloud"

  ## Keycloak Architecture override to enable HA or standalone
  keycloak:
    domain: &keycloakDomain ""
    nodePorts:
      http: &keycloakNodePortHTTP "32701"
      https: &keycloakNodePortHTTPS "32702"

  frontend:
    userPortal:
      domain: &userDomain ""
      tlsSecret: &userTls ""
    # For Production environment we require kyc status validation
    # However, for dev and test environments we should be able to skip
    # these validations
    # Setting skipKyc true will bypass this validation
    # Note: This configuration should not be used for Production env
    skipKyc: false

nodeSelector: {} 

replicaCount: 1

image: "fluid-console"

service:
  nodePort: "32500"

resources: 
  limits:
    cpu: 400m
    # memory: 128Mi
  requests:
    cpu: 100m
    memory: 200Mi

## Only use when https.enabled is set true
## Else leave empty
ingress:
  tlsSecret: ""
  hostname: ""
  class: nginx

## Enabled Services
enabledServices: ""

docsURL: ""

additionalURLs:
  appStoreURL: ""
  secComplianceURL: ""
  userRegisterURL: ""
  pamIframeURL: ""
  quartzURL: ""
  cobaltURL: ""
  cloudSecurityPosture: ""
  virtualSuiteDashboard: ""
  ticketSupport: ""

objectStorage:
  maxBucketSize: ""

blockStorage: 
  maxSize: ""

## Accommodate large uploads for the container registry
## Default value: 10G
clientMaxBodySize: '10G'

## Enable ChatBot on the GUI
chatbot:
  enabled: false

extraRoutes: []

certs:
  ingress:
    caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdBVENDQSttZ0F3SUJBZ0lVVHE4bnNMQU82M0YrK0hodjQvOExVU0E2b0w0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZOHhDekFKQmdOVkJBWVRBa2xPTVFzd0NRWURWUVFJREFKTFFURVNNQkFHQTFVRUJ3d0pRbUZ1WjJGcwpiM0psTVJNd0VRWURWUVFLREFwRGIzSmxaR2RsTG1sdk1SVXdFd1lEVlFRTERBeERiRzkxWkVOdmJYQmhjM014CkR6QU5CZ05WQkFNTUJuTmxjblpsY2pFaU1DQUdDU3FHU0liM0RRRUpBUllUY0hKaFltaHFiM1JBWTI5eVpXUm4KWlM1cGJ6QWVGdzB5TWpBME1qUXhNVFE0TUROYUZ3MHpNakEwTWpFeE1UUTRNRE5hTUlHUE1Rc3dDUVlEVlFRRwpFd0pKVGpFTE1Ba0dBMVVFQ0F3Q1MwRXhFakFRQmdOVkJBY01DVUpoYm1kaGJHOXlaVEVUTUJFR0ExVUVDZ3dLClEyOXlaV1JuWlM1cGJ6RVZNQk1HQTFVRUN3d01RMnh2ZFdSRGIyMXdZWE56TVE4d0RRWURWUVFEREFaelpYSjIKWlhJeElqQWdCZ2txaGtpRzl3MEJDUUVXRTNCeVlXSm9hbTkwUUdOdmNtVmtaMlV1YVc4d2dnSWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDMS9tSGpLTnl5UGxvUldFbWRIQkczSDA5RDRYS3pWQit4CmZ4ZEZjckhab3RsVTUxSXBFTjRBYU9sMDZwR2JUbHBpWjc3Qm95RnR1TUg5QXRXUUpHK01JWVpBRklucXZQVzAKVW13VjhoQWtNd3UrVDBMMTE3RWVvRlA0WFlkN1JlTzBGQVVnLzNWeVJUdGpPdTRYNVhpaWpWdThaVm04enNuMQoxSHFaa0dUaFZIZHV6SkhhTXp3QjMxMTRPYk5VbTdQeEhGbi9LMVFRRlE1M0I5RWFsSmtXdCtvY2VnYkpFUlhtCitJVEkzMGtwbGZxcjJhVVJWVHhXaU9VNUIxSW5GOVhvQmFpYTJTQmNPK0pMOWRFSCswNS9aTWpUVlovRGV1bzIKam4rU2lORjBRK3JBVFAwZDJCUVBUQzJIU3RYbDlUSTRzOTcyaVBVMXdWaW1nNjZUTnpRcHh6dlFwQnhlNE1MQgozbkcyUk5wYUxnTk93Q1p1MS9oNnVsVlhIcVFBVytVdzlsYzE0K2xLOGg0c3BEQm1VUTl2N0ExOG1zMURtY0x0CmN4aVJUV1J6TkxSbDdRbzlpWU9zek00TGp3QW82eDdYbldia0hxVlFINVdHck95WGQvMjEzWUJTUENIUUNycEIKeWRiSWFZNXl6bEQrakJXamxacVJRbTl6Z2lsSDlZTTVjaHA1R0dtY2Q1bDdWaGh4Z083REZnVE10cHVNeEg2cgppMmxiU3ZRdzd2TnBQMjNQdjNLbmFTYyszTUszQzBqNDAxekNOSW9JcGhXcXB3SDdEWTBhS1ZkU1gzK3EvME1qCnpacEtCY2V6bFFEZjh1OXpXbnQways2MkFrMnNBYXcvMU1SSWNKcjNFSG9vOW5VSmIxUTJaelJPVlBhREtHaW8KK2M4MWJWaVVJUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVeTZZTzdkNi8wRzB3N01US2VHbU56YW1pb0dJdwpId1lEVlIwakJCZ3dGb0FVeTZZTzdkNi8wRzB3N01US2VHbU56YW1pb0dJd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFUNTArTjh2WmpIWDN5N2c5UHZ2M1BYc3RrdFY4RHJUNG1qWUcKV0tEYUxQRW9tNDhUVnNqS1QvYXl1Vlk1ZFc2TGgwRXFOMW5NVnNoMlJoTUQ5enZVbFVzS0tjK09FdWdTVnZNcAphRE9mUjRsT25oaEN6UVRGdDJpUXg5WnUxZFpYUlVyMTJ3WUxvSXpiZHRoNUZaNWtQYmF2SzhFRVVnbWpray9xCm9veXhBSXh4QUhGZUY4aVVsekJTcWxCQ3ViYWZDYW9ZMFBoQktaQnVKenRpYjdRSGR6bFdKbVhTY2FrRkNpWjgKN3Eyam5yUlVpTEcvUktUd2FNOU5BVWVCcVBKdFlVbzN6VG4ydmZUYlNKZ1J4QWxDRnNEWTF5ZTArVVFqYnVTVgpEbTlnb1N0Um5jVmxyWWNwUjc1MXpsejNlQ2R2UzRYTUFJMWJNU01VZVFBUHRUcTZPNzFGOGtXL2lFMjNENHFNCnRYemRRV0V0YlIxeFpEOGdERXE2VlM1WGNieHY4ZmhOc0xNQW9Ma3JwblFGNWZUNDYyTTVQNHBqWkFzVGJMRHoKTzRrV0dhbkFIUW9ROGpwc3NmbEU4Yjl3SHlISjdlbko0UWFaemdzd0tTYUt3NXpZNlhBa0NGOHZXZEZNZjg5TApaVjlFOFd3WVFQbUowV2UreC9wd3FITThZMTMzR0txSG81d2c1aUNQenlkbTJ5SUFNYmhPcjRKbU9jMG5OaThlCjM3ZTRoUkRsODRsbk9OVVBqNWlJU3F5QWI4VVBWV3Q3aU1oQSt0b091ZnY2RVZaNGlLZFluMU41TG1ROGE5eUYKOVpMdlZJbnNHNlVRVzRlVkk3cjgvWTFBbE12eVVyN296ODlPVmx5YkFuUmVxenl2M2xFZFRvTmtyY0dtY2hodgpRQ0dvT3ZrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdBVENDQSttZ0F3SUJBZ0lVVHE4bnNMQU82M0YrK0hodjQvOExVU0E2b0w0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZOHhDekFKQmdOVkJBWVRBa2xPTVFzd0NRWURWUVFJREFKTFFURVNNQkFHQTFVRUJ3d0pRbUZ1WjJGcwpiM0psTVJNd0VRWURWUVFLREFwRGIzSmxaR2RsTG1sdk1SVXdFd1lEVlFRTERBeERiRzkxWkVOdmJYQmhjM014CkR6QU5CZ05WQkFNTUJuTmxjblpsY2pFaU1DQUdDU3FHU0liM0RRRUpBUllUY0hKaFltaHFiM1JBWTI5eVpXUm4KWlM1cGJ6QWVGdzB5TWpBME1qUXhNVFE0TUROYUZ3MHpNakEwTWpFeE1UUTRNRE5hTUlHUE1Rc3dDUVlEVlFRRwpFd0pKVGpFTE1Ba0dBMVVFQ0F3Q1MwRXhFakFRQmdOVkJBY01DVUpoYm1kaGJHOXlaVEVUTUJFR0ExVUVDZ3dLClEyOXlaV1JuWlM1cGJ6RVZNQk1HQTFVRUN3d01RMnh2ZFdSRGIyMXdZWE56TVE4d0RRWURWUVFEREFaelpYSjIKWlhJeElqQWdCZ2txaGtpRzl3MEJDUUVXRTNCeVlXSm9hbTkwUUdOdmNtVmtaMlV1YVc4d2dnSWlNQTBHQ1NxRwpTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDMS9tSGpLTnl5UGxvUldFbWRIQkczSDA5RDRYS3pWQit4CmZ4ZEZjckhab3RsVTUxSXBFTjRBYU9sMDZwR2JUbHBpWjc3Qm95RnR1TUg5QXRXUUpHK01JWVpBRklucXZQVzAKVW13VjhoQWtNd3UrVDBMMTE3RWVvRlA0WFlkN1JlTzBGQVVnLzNWeVJUdGpPdTRYNVhpaWpWdThaVm04enNuMQoxSHFaa0dUaFZIZHV6SkhhTXp3QjMxMTRPYk5VbTdQeEhGbi9LMVFRRlE1M0I5RWFsSmtXdCtvY2VnYkpFUlhtCitJVEkzMGtwbGZxcjJhVVJWVHhXaU9VNUIxSW5GOVhvQmFpYTJTQmNPK0pMOWRFSCswNS9aTWpUVlovRGV1bzIKam4rU2lORjBRK3JBVFAwZDJCUVBUQzJIU3RYbDlUSTRzOTcyaVBVMXdWaW1nNjZUTnpRcHh6dlFwQnhlNE1MQgozbkcyUk5wYUxnTk93Q1p1MS9oNnVsVlhIcVFBVytVdzlsYzE0K2xLOGg0c3BEQm1VUTl2N0ExOG1zMURtY0x0CmN4aVJUV1J6TkxSbDdRbzlpWU9zek00TGp3QW82eDdYbldia0hxVlFINVdHck95WGQvMjEzWUJTUENIUUNycEIKeWRiSWFZNXl6bEQrakJXamxacVJRbTl6Z2lsSDlZTTVjaHA1R0dtY2Q1bDdWaGh4Z083REZnVE10cHVNeEg2cgppMmxiU3ZRdzd2TnBQMjNQdjNLbmFTYyszTUszQzBqNDAxekNOSW9JcGhXcXB3SDdEWTBhS1ZkU1gzK3EvME1qCnpacEtCY2V6bFFEZjh1OXpXbnQways2MkFrMnNBYXcvMU1SSWNKcjNFSG9vOW5VSmIxUTJaelJPVlBhREtHaW8KK2M4MWJWaVVJUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVeTZZTzdkNi8wRzB3N01US2VHbU56YW1pb0dJdwpId1lEVlIwakJCZ3dGb0FVeTZZTzdkNi8wRzB3N01US2VHbU56YW1pb0dJd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFUNTArTjh2WmpIWDN5N2c5UHZ2M1BYc3RrdFY4RHJUNG1qWUcKV0tEYUxQRW9tNDhUVnNqS1QvYXl1Vlk1ZFc2TGgwRXFOMW5NVnNoMlJoTUQ5enZVbFVzS0tjK09FdWdTVnZNcAphRE9mUjRsT25oaEN6UVRGdDJpUXg5WnUxZFpYUlVyMTJ3WUxvSXpiZHRoNUZaNWtQYmF2SzhFRVVnbWpray9xCm9veXhBSXh4QUhGZUY4aVVsekJTcWxCQ3ViYWZDYW9ZMFBoQktaQnVKenRpYjdRSGR6bFdKbVhTY2FrRkNpWjgKN3Eyam5yUlVpTEcvUktUd2FNOU5BVWVCcVBKdFlVbzN6VG4ydmZUYlNKZ1J4QWxDRnNEWTF5ZTArVVFqYnVTVgpEbTlnb1N0Um5jVmxyWWNwUjc1MXpsejNlQ2R2UzRYTUFJMWJNU01VZVFBUHRUcTZPNzFGOGtXL2lFMjNENHFNCnRYemRRV0V0YlIxeFpEOGdERXE2VlM1WGNieHY4ZmhOc0xNQW9Ma3JwblFGNWZUNDYyTTVQNHBqWkFzVGJMRHoKTzRrV0dhbkFIUW9ROGpwc3NmbEU4Yjl3SHlISjdlbko0UWFaemdzd0tTYUt3NXpZNlhBa0NGOHZXZEZNZjg5TApaVjlFOFd3WVFQbUowV2UreC9wd3FITThZMTMzR0txSG81d2c1aUNQenlkbTJ5SUFNYmhPcjRKbU9jMG5OaThlCjM3ZTRoUkRsODRsbk9OVVBqNWlJU3F5QWI4VVBWV3Q3aU1oQSt0b091ZnY2RVZaNGlLZFluMU41TG1ROGE5eUYKOVpMdlZJbnNHNlVRVzRlVkk3cjgvWTFBbE12eVVyN296ODlPVmx5YkFuUmVxenl2M2xFZFRvTmtyY0dtY2hodgpRQ0dvT3ZrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    privKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQzEvbUhqS055eVBsb1IKV0VtZEhCRzNIMDlENFhLelZCK3hmeGRGY3JIWm90bFU1MUlwRU40QWFPbDA2cEdiVGxwaVo3N0JveUZ0dU1IOQpBdFdRSkcrTUlZWkFGSW5xdlBXMFVtd1Y4aEFrTXd1K1QwTDExN0Vlb0ZQNFhZZDdSZU8wRkFVZy8zVnlSVHRqCk91NFg1WGlpalZ1OFpWbTh6c24xMUhxWmtHVGhWSGR1ekpIYU16d0IzMTE0T2JOVW03UHhIRm4vSzFRUUZRNTMKQjlFYWxKa1d0K29jZWdiSkVSWG0rSVRJMzBrcGxmcXIyYVVSVlR4V2lPVTVCMUluRjlYb0JhaWEyU0JjTytKTAo5ZEVIKzA1L1pNalRWWi9EZXVvMmpuK1NpTkYwUStyQVRQMGQyQlFQVEMySFN0WGw5VEk0czk3MmlQVTF3VmltCmc2NlROelFweHp2UXBCeGU0TUxCM25HMlJOcGFMZ05Pd0NadTEvaDZ1bFZYSHFRQVcrVXc5bGMxNCtsSzhoNHMKcERCbVVROXY3QTE4bXMxRG1jTHRjeGlSVFdSek5MUmw3UW85aVlPc3pNNExqd0FvNng3WG5XYmtIcVZRSDVXRwpyT3lYZC8yMTNZQlNQQ0hRQ3JwQnlkYklhWTV5emxEK2pCV2psWnFSUW05emdpbEg5WU01Y2hwNUdHbWNkNWw3ClZoaHhnTzdERmdUTXRwdU14SDZyaTJsYlN2UXc3dk5wUDIzUHYzS25hU2MrM01LM0MwajQwMXpDTklvSXBoV3EKcHdIN0RZMGFLVmRTWDMrcS8wTWp6WnBLQmNlemxRRGY4dTl6V250MGsrNjJBazJzQWF3LzFNUkljSnIzRUhvbwo5blVKYjFRMlp6Uk9WUGFES0dpbytjODFiVmlVSVFJREFRQUJBb0lDQUNBbTByQkk5Y1JmazVYZzNSQnVkd3E4Cjgwbnd1RXpLSGRkRHRwN0VSbnRHYzlLMkV5UENJUlk5Y3BEL0o3NGlONEdQQm5vN0Vackt1eXF4cDMwUmtzdFUKMk56VlJCQStWY0lIbGFUQzRPc2tRWHpiajk3U3ZpM0U4VkM5WlVQMzh1UkxiU1NKUFB4MUVxclRMR0Q0WHptSQpjNTV5NFVtajFyWWhWWTl2blFMWjQwZWx5RmFlR29uU0pqY3BLbTlXR3BJTUNqSTBPMk9qOUt3K3EwaGczRExSClJ3REU1aEg3ZkwwVFJwSWVNRlN5ZEZpTDJNZVpJVkhBV1k2YnBuM1ZqaXF4WlRvR0JkdUZrTk1PbUdFcW1wR1QKQW8ralh0Z3dETlNhbEJzVkpMdS9pK2R4TW41bFFCWDd4VWRUaHpwYStRWmZjSkpwVzdpbGNiM3BJWnhNY21CcQoxSWdLaEVpYnh5SzMxYjhtTlU2REVOdG12a1hTaUFOTUszL3RyTGJCaGtmZUswSmxTT2hwb3U1bk1YV1hLTkQzClV3dlVMbDN6STV3UVdvZnRRK3gzZWNwY29hM2x3bis0d3g2WnBHYnhyaGwvUlhLUG53eE51MkVYdG9JT3Z3d1gKZW0zVTdoTm1vaEh1Uy9hOTBEMkpCYmE4QnR0WEdudk1vWHRuZ0dBczlCbjlQTlNWa21UM2pFTUwzOVJYZGRCRwowemUrejdncllQZGN3N1R4R0tMS1BXUkZBa1dTZm5EYy9tVlE3djVkSEl1T1JMYmJ2NHIrL1NCV3R3Sjg0YkdxCnRyZlQvNlExVTZOUS95a3hseUErc3lRcjZEV2hzWkRGODB2MHVKV0FlZnJpZTFtL0c0YitOejB1cFRNY2xKa1QKSmlabVBNaVdld3cwOTRGaWxYZUJBb0lCQVFEY0JIdW11a2MrNksrckhoaVdLb29mR25YdzQ3eHl5YlBZK0FYNgpsSnRtTnYxOExhRUI4V0pnSFA4L25Ic2hVMGh5UGM4Wk9jaEg3elphUTZDZnhOdjB3c1VOMkJ2aHFKRDZpMTBuCjZUTVlXOGVRQk5YcTFSUDJmTUxLZnRaOWJqdk1UL00rOEV3YkNjQ25TbStGQmlVNUtzblBQbTAzRG1BTjMvbW0KL0lXN2daRUk5RXZmaXVsZFc4c3dWcGdTTFc4NXAvQTJXb2xpZ3ZuU0paRmpSOW52VEp6Q0dlVHdwdDNnVlQ3bwoxMGpuL2VZQW1XZXlEUnpXS3BrR25WbHdaRGlkS0hUdUxacGVxc0J6bHRyeTUzdFNzUGc4ckhFS21MY3c3Lzl5CnhYVWNZWGoreWRZclZNUzIrMEtkVHdtaDVNNjZvWnRqL2lEOGk5elV4Q2tUbmVnWkFvSUJBUURUd2ZLMHJPUUcKSnd6ZlZ0S0hSbXFQbStRQnJqdFZGdkh5eFRFWkt0aTZJby9rREhpYzZNcVRieWZ6YXRHK3lKUG5rY2swd2kxUwp3L0lXOWhtdEkraUs4RGVHdFFRc0VmL1lZNElJQ08zUlBEK21HcTlwVkpldXNxT0l3WGlFQllmTytqYndNYnFxCnpiajZua2RBelRjTHVYaFFka3JNK1MzUjM0K1hicEZnVnpUSkRFK1MxdkxxZEVueXFXUFJmOENoM2xTRXNCN3oKN3ltL1kxTkl5eW82RUlXWDJWSlFhT3ZvUkhCaEpBRms1ZmU5MXhpRlE5dkt5U3BrN2Q2Q2ZXdkdvc0lrVjVhTgp3cHNPbXMwSFNGMmhXN3kvMlhZNE0xaUhDTURvZnBHMExGSnZFYWhqVVI0RFpBYTRuV2RKVG81SkRBSm1PR1g5Cm5WTHVzMi9rVFMxSkFvSUJBUUNZbjJ0L1R2MFpRS1NMbVljSXRGMjRFY3o2MjUvZ0tOZGZqVDNvZzZvQkQraHIKZWVPVXkzT29wTFRUMWFMOGpSOVdVRllYYzZQaGNxbExtRm9XT3FNeWVPSGxKcUxBdVFSSktOL29UYmFxRVJDdwpjUXBMcXAvOGZyTkpjUTh0VjRpWHhHWkNwTUxHaHM5anZSajdPRFllSC9aNmt4MkQ4YTdrTVJpbm84akpONm42CmdpMFgxdTduV2tQck5rYXJaV1VnbzhUWWo1bDZBczExMzZXcEx6Q1k5WlpRZDFIL05tSDN1bXEzYnBBZWpsdzgKMGkzQ3I2SHZWd0ZzT3o3TjNsZi9mUThRSWdaUjRUVTdlY3hNY0JOMlcxajREYzhrd0tkamhUaTR6d3pjTVNtVAo1VU55TDQxK09YSU9XY09lMEhBdnV1ZG1SK1Z1Q3orWFFMUVY3WllSQW9JQkFBNlJzSDRueXdSMVdWaGdZOW0wCnlZNFozcVVTOUxnVS9RNkQ3SzNibWMrc294UEFtK2ZIeUhBK1hKUk56Q0tCTUZQbFh0K0hZSkRxTkZUS0Y5Z20KdVZBZDJPUW12aU8rRlVreEIzaEFEUVN4VFh2REtFQnA5b21wZHNEbzlyNjJsckp4MnFmSjlCcmVUcFRIb1FWZgpXU013WG92Q3A4RFVnQWVKaHhxWEc5OXlBSXE0a3h6Nk52cFVoK1h2SzVQMVl5NS8ybmJLbTBhVE5OOGJHVmJQCnk1YjFIZ3ZsZ3RsUGJyT3JTY1FWTXhkYkR5RjdsQTlQTE9jVjBobmhsOGFJbElxMUZnQmtHbEtraWdDR1BBYjkKUHB2a2NPY09NaWtKdDFTTEVLS3VXcDMzMHJBYm1lZERaSG85UG8wakgwRVc2NGt4RDFVekdpbEowclBqbXBZdApqU2tDZ2dFQUhoanU4ZXBUWGZoT2ZPcnh4c1JnY1EwY2tEczNZM0h3MThpVHhDWXM5RmJDT1FORVhWcUI0S2xMCmlJcHNmNVU4MnBjRHFGU1ZDc1U3REVTeDZDL0VFbFg1TVE1UHJPN3BEVE9RTFVQRHNwNFNid1o4bjFHenZrYkIKdHRjYktJRVJsTVhvL1dWQUtqWU16emg2SzRXQlVCWWxuSndhbk5wM05pVEpRM3dab0hHOWR5K2Y5MnRlcmgzcQpOd1JoNTVVd2ZrWXArYzZ6WGF1YUtjN2p6ZzJzVVlnbllYZTZQcHU1cmVyUmVaQ205c2JsVllxLytGQUw0bWRxCkM0ZjVGZFFBT0ROQVRLeVMya2IwdytWNElMcUFzUHdCWDBHWW5DcWYxWGdtSGpKNEMzbStIS20xQ043SmV6T2wKd0tDS2U2bDNCZjdKblpmMWtBLzErVFhtVFU4K0NRPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=