apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ccp-extension-logs-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: ccp-extension
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
