apiVersion: v1
kind: Service
metadata:
  name: ccp-extension
  namespace: {{ .Release.Namespace }}
  labels:
    app: ccp-extension
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
      app: ccp-extension
