apiVersion: v2
appVersion: "0.1"
dependencies:
- name: helper
  repository: file://components/helper
  version: 0.1.0
- name: repository-cred
  repository: file://components/repository-cred
  version: 0.1.0
- condition: global.cloudManager.enabled
  name: cloud-manager
  repository: file://components/cloud-manager
  version: 0.1.0
- condition: global.workflowManager.enabled
  name: workflow-manager
  repository: file://components/workflow-manager
  version: 0.1.0
- condition: global.containerRegistry.enabled
  name: container-registry
  repository: file://components/container-registry
  version: 0.1.0
- condition: global.baremetalManager.enabled
  name: baremetal-manager
  repository: file://components/baremetal-manager
  version: 0.1.0
- condition: global.metering.enabled
  name: metering
  repository: file://components/metering
  version: 0.1.0
- condition: global.storagePlugin.enabled
  name: storage-plugin
  repository: file://components/storage-plugin
  version: 0.1.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.52.1
- name: auth-service
  repository: file://components/auth-service
  version: 0.1.0
- condition: global.networkManager.enabled
  name: network-manager
  repository: file://components/network-manager
  version: 0.1.0
- condition: global.tenantManagementService.enabled
  name: tenant-management-service
  repository: file://components/tenant-management-service
  version: 0.1.0
#####
- condition: global.userPortal.enabled
  name: userPortal
  repository: 'file://components/user-portal'
  version: 0.1.0
- condition: global.adminServices.enabled
  name: adminServices
  repository: 'file://components/admin'
  version: 0.1.0
- condition: global.computeService.enabled
  name: computeService
  repository: 'file://components/compute-service'
  version: 0.1.0
- condition: global.volumeService.enabled
  name: volumeService
  repository: 'file://components/volume-service'
  version: 0.1.0
- condition: global.coremgmtService.enabled
  name: coremgmtService
  repository: 'file://components/core-mgmt-service'
  version: 0.1.0
- condition: global.neutronService.enabled
  name: neutronService
  repository: 'file://components/neutron-service'
  version: 0.1.0
- condition: global.autoscalingService.enabled
  name: autoscalingService
  repository: 'file://components/autoscaling'
  version: 0.1.0
- condition: global.archivalStorage.enabled
  name: archivalStorage
  repository: 'file://components/archival-storage'
  version: 0.1.0
- condition: postgres-operator.enabled
  name: postgres-operator
  repository: oci://registry-1.docker.io/coredgehelm
  version: 1.12.2
- condition: global.keycloak.highavailability
  name: keycloak-ha
  repository: oci://registry-1.docker.io/coredgehelm
  version: 0.1.4
- condition: pgadmin.enabled
  name: pgadmin
  repository: 'file://components/pgadmin'
  version: 0.1.0
- condition: global.notificationService.enabled
  name: notificationService
  repository: 'file://components/notification-service'
  version: 0.1.0
- condition: global.certificatesManager.enabled
  name: certificatesManager
  repository: 'file://components/certificates-manager'
  version: 0.1.0
- condition: global.ccpExtension.enabled
  name: ccpExtension
  repository: 'file://components/ccp-extension'
  version: 0.1.0
- condition: global.vmconsole.enabled
  name: vmconsole
  repository: 'file://components/vmconsole'
  version: 0.1.0
- condition: global.tcpwaveExtension.enabled
  name: tcpwave-extension
  repository: oci://registry-1.docker.io/coredgehelm
  version: 0.1.0
description: Helm chart for Coredge Cloud Suite
name: ccs
version: 0.1.0
