apiVersion: v1
kind: Service
metadata:
  name: autoscaling-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: autoscaling-service
spec:
  type: ClusterIP
  ports:
  - port: 7181
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: autoscaling-service
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaling-service-celery
  namespace: {{ .Release.Namespace }}
  labels:
    app: autoscaling-service-celery
spec:
  type: ClusterIP
  ports:
  - port: 7181
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
      app: autoscaling-service-celery