apiVersion: v1
kind: Service
metadata:
  name: container-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: container-registry
spec:
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: oci-v2
    port: 8020
    targetPort: 8020
    protocol: TCP
  - name: auth
    port: 8070
    targetPort: 8070
    protocol: TCP
  - name: websocket
    port: 9080
    targetPort: 9080
  selector:
    app: container-registry
