name:  Helm upgrade

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Backup values.yaml to home directory backup folder
        run: |
          BACKUP_DIR="/home/ubuntu/ccs-helm-charts/backup"
          mkdir -p "$BACKUP_DIR"
          TIMESTAMP=$(date +%Y%m%d)
          cp ./ccs-helm-charts/helm/values.yaml "$BACKUP_DIR/values.yaml.$TIMESTAMP"
          echo "Backup saved to $BACKUP_DIR/values.yaml.$TIMESTAMP"

      - name: Add required Helm repo
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Helm upgrade/install fluid chart
        working-directory: ./ccs-helm-charts/helm  
        run: |
          helm dependency build
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A
