name: Deploying Nginx and Helm upgrade

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Backup values.yaml file
        working-directory: ./helm
        run: |
          BACKUP_DIR="../backup"
          mkdir -p "$BACKUP_DIR"
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          cp values.yaml "$BACKUP_DIR/values.yaml.$TIMESTAMP"
          echo "Backup saved to $BACKUP_DIR/values.yaml.$TIMESTAMP"

      - name: Helm dependency build
        working-directory: ./helm
        run: helm dependency build

      - name: Helm upgrade/install fluid chart
        working-directory: ./helm
        run: |
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A
