name: Upgrading FLuid using the Helm Upgrade

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Helm upgrade/install fluid chart with values.yaml backup
        working-directory: ./helm
        run: |
          # Create backup directory if not exists
          mkdir -p backup

          # Backup values.yaml with timestamp
          cp values.yaml backup/values.yaml.$(date +%Y%m%d%H%M%S)

          # Build dependencies and upgrade/install
          helm dependency build
          helm upgrade  fluid . -f values.yaml -n fluid --create-namespace

          helm list -A
