name: Fluid upgrade using helm 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Helm upgrade/install fluid chart with values.yaml backup
        working-directory: ./helm
        run: |
          mkdir -p backup
          cp values.yaml backup/values.yaml.$(date +%Y%m%d%H%M%S)
          helm dependency build
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A

      - name: Upload backup artifact
        uses: actions/upload-artifact@v3
        with:
          name: helm-values-backup
          path: ./helm/backup/
