name: Deploying Nginx and Helm upgrade

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Helm upgrade/install fluid chart
        working-directory: ./helm  
        run: |
          helm dependency build
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A
