name: Upgrading fluid using helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Configure AWS CLI for MinIO
        run: |
          mkdir -p ~/.aws
          cat <<EOF > ~/.aws/credentials
          [default]
          aws_access_key_id = minioadmin
          aws_secret_access_key = minioadmin123
          EOF

          cat <<EOF > ~/.aws/config
          [default]
          region = us-east-1
          output = json
          EOF

      - name: Backup PostgreSQL and upload to MinIO
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          kubectl exec -n fluid ccs-postgresql-cluster-0 -- \
            env PGPASSWORD="${{ secrets.POSTGRES_PASSWORD }}" pg_dump -U ccs cloud > cloud_backup_$TIMESTAMP.sql
          aws --endpoint-url http://172.16.109.86:9000 s3 cp cloud_backup_$TIMESTAMP.sql s3://minio-bucket/cloud_backup_$TIMESTAMP.sql
          rm cloud_backup_$TIMESTAMP.sql

      - name: Backup MongoDB and upload to MinIO
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          kubectl exec -n fluid configdb-0 -- \
            mongodump --username sigma --password "${{ secrets.MONGO_PASSWORD }}" --authenticationDatabase admin --archive --gzip > mongodb_backup_$TIMESTAMP.gz
          aws --endpoint-url http://172.16.109.86:9000 s3 cp mongodb_backup_$TIMESTAMP.gz s3://minio-bucket/mongodb_backup_$TIMESTAMP.gz
          rm mongodb_backup_$TIMESTAMP.gz

      - name: Backup values.yaml and upload to MinIO
        working-directory: ./helm
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          cp values.yaml values.yaml.$TIMESTAMP
          aws --endpoint-url http://172.16.109.86:9000 s3 cp values.yaml.$TIMESTAMP s3://minio-bucket/values.yaml.$TIMESTAMP
          rm values.yaml.$TIMESTAMP

      - name: Helm registry login
        run: |
          helm registry login docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Helm dependency build
        working-directory: ./helm
        run: helm dependency build

      - name: Helm upgrade/install fluid chart
        working-directory: ./helm
        run: |
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A
