name: Deploying Nginx and Helm upgrade

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Helm charts folder to workspace
        run: cp -r ~/ccs-helm-charts $GITHUB_WORKSPACE/ccs-helm-charts

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_RAW }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config get-contexts

      - name: Backup values.yaml inside ccs-helm-charts/helm/backup
        working-directory: ./ccs-helm-charts/helm
        run: |
          mkdir -p backup
          cp values.yaml backup/values.yaml.$(date +%Y%m%d%H%M%S)

      - name: Helm upgrade/install fluid chart
        working-directory: ./ccs-helm-charts/helm
        run: |
          helm dependency build
          helm upgrade --install fluid . -f values.yaml -n fluid --create-namespace
          helm list -A
